services:
  web-dev:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    env_file:
      - .env.dev
    environment:
      DB_HOST: db-dev
      DB_PORT: "5432"
      DB_USER: shopnest
      DB_NAME: shopnest
      DB_PASSWORD: ${DEV_DB_PASSWORD}
      PAYMENT_ENCRYPTION_KEY: ${DEV_PAYMENT_ENCRYPTION_KEY}
    depends_on:
      - db-dev
    networks:
      - shopnest-dev-net

  db-dev:
    image: postgres:17.0
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: shopnest
      POSTGRES_PASSWORD: ${DEV_DB_PASSWORD}
      POSTGRES_DB: shopnest
    volumes:
      - pgdata-dev:/var/lib/postgresql/data
    networks:
      - shopnest-dev-net

  nginx-dev:
    image: nginx:latest
    volumes:
      - type: bind
        source: ./nginx.dev.conf
        target: /etc/nginx/nginx.conf
        read_only: true
        bind:
          create_host_path: false
    ports:
      - "8080:80"
    depends_on:
      - web-dev
    networks:
      - shopnest-dev-net

volumes:
  pgdata-dev:

networks:
  shopnest-dev-net:
