import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

const read = (path: string) => readFile(path, "utf8");

test("marketing translations stay aligned", async () => {
  const [en, he] = await Promise.all([
    read("src/messages/en.json").then(JSON.parse),
    read("src/messages/he.json").then(JSON.parse),
  ]);
  assert.deepEqual(Object.keys(en.Marketing).sort(), Object.keys(he.Marketing).sort());
});

test("public marketing surface stays tenantless", async () => {
  const paths = [
    "src/app/page.tsx",
    "src/app/(marketing)/_components/MarketingHeader.tsx",
    "src/app/(marketing)/_components/MarketingFooter.tsx",
  ];
  const sources = await Promise.all(paths.map(read));
  const source = sources.join("\n");
  assert.doesNotMatch(source, /@\/drizzle\/db|@\/lib\/tenant-context|@\/lib\/tenant\b/);
  assert.doesNotMatch(source, /TenantLink/);
});

test("marketing CTAs target public acquisition routes", async () => {
  const sources = await Promise.all([
    read("src/app/(marketing)/_components/MarketingHeader.tsx"),
    read("src/app/(marketing)/_components/HeroSection.tsx"),
  ]);
  const source = sources.join("\n");
  assert.match(source, /href="\/signup"/);
  assert.match(source, /href="\/login"/);
  assert.match(source, /href="\/examples"/);
  assert.match(source, /min-h-11/);
});

test("homepage composes every acquisition section", async () => {
  const source = await read("src/app/page.tsx");
  for (const name of [
    "MarketingHeader",
    "HeroSection",
    "WhyShopNestSection",
    "CapabilitiesSection",
    "HowItWorksSection",
    "PricingPreview",
    "DemoStoresSection",
    "FaqSection",
    "FinalCtaSection",
    "MarketingFooter",
  ]) {
    assert.match(source, new RegExp(name));
  }
});

test("public informational routes remain tenantless while merchant auth routes are functional", async () => {
  const informational = await Promise.all([
    read("src/app/(marketing)/features/page.tsx"),
    read("src/app/(marketing)/pricing/page.tsx"),
    read("src/app/(marketing)/examples/page.tsx"),
    read("src/app/(marketing)/faq/page.tsx"),
  ]);
  for (const source of informational) assert.match(source, /href="\/"/);

  const [login, signup] = await Promise.all([
    read("src/app/(marketing)/login/page.tsx"),
    read("src/app/(marketing)/signup/page.tsx"),
  ]);
  assert.match(login, /MerchantLoginForm/);
  assert.match(signup, /MerchantSignupForm/);
  assert.doesNotMatch(
    login + signup,
    /@\/drizzle\/db|@\/lib\/tenant-context|TenantLink|getDbForTenant|getTenant\(/
  );
});

test("marketing surface is RTL-safe, responsive and CSS-driven", async () => {
  const paths = [
    "src/app/(marketing)/_components/MarketingHeader.tsx",
    "src/app/(marketing)/_components/HeroSection.tsx",
    "src/app/(marketing)/_components/WhyShopNestSection.tsx",
    "src/app/(marketing)/_components/CapabilitiesSection.tsx",
    "src/app/(marketing)/_components/HowItWorksSection.tsx",
    "src/app/(marketing)/_components/PricingPreview.tsx",
    "src/app/(marketing)/_components/DemoStoresSection.tsx",
    "src/app/(marketing)/_components/FaqSection.tsx",
    "src/app/(marketing)/_components/FinalCtaSection.tsx",
  ];
  const source = (await Promise.all(paths.map(read))).join("\n");
  assert.doesNotMatch(source, /space-x-|\bml-|\bmr-/);
  assert.doesNotMatch(source, /innerWidth|matchMedia|ResizeObserver/);
  assert.match(source, /grid-cols-1/);
  assert.match(source, /lg:grid-cols-/);
  assert.match(source, /<details/);
  assert.match(source, /<summary/);
});

test("root metadata uses ShopNest defaults", async () => {
  const source = await read("src/app/layout.tsx");
  assert.match(source, /default: "ShopNest"/);
  assert.match(source, /template: "%s \| ShopNest"/);
  assert.doesNotMatch(source, /Create Next App|Generated by create next app/);
  assert.match(source, /dir=\{locale === "he" \? "rtl" : "ltr"\}/);
});
