import type { Metadata } from "next";

import { Montserrat } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import ToastProvider from "./components/ToastProvider";
import { NextIntlClientProvider } from "next-intl";
import { getLocale, getMessages } from "next-intl/server";
import { getTenant } from "@/lib/tenant-context";
import { TenantProvider } from "@/context/TenantContext";

const montserrat = Montserrat({
  variable: "--font-sans",
  weight: ["400", "700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const messages = await getMessages();
  const locale = await getLocale();
  const tenant = await getTenant();

  return (
    <html lang={locale} dir={locale === "he" ? "rtl" : "ltr"}>
      <body
        className={cn(
          "bg-background min-h-screen flex flex-col font-sans antialiased",
          montserrat.variable
        )}
      >
        <TenantProvider basePath={tenant?.basePath ?? ""}>
          <NextIntlClientProvider messages={messages}>
            {children}
          </NextIntlClientProvider>
        </TenantProvider>
        <ToastProvider />
      </body>
    </html>
  );
}
