import type { Metadata } from "next";

import { Roboto, Montserrat, Lato } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import ToastProvider from "./components/ToastProvider";

const roboto = Roboto({
  variable: "--font-sans",
  weight: ["400", "700"],
  subsets: ["latin"],
});

const lato = Lato({
  variable: "--font-sans",
  weight: ["400", "700"],
  subsets: ["latin"],
});

const montserrat = Montserrat({
  variable: "--font-sans",
  weight: ["400", "700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="he" dir="rtl">
      <body
        className={cn(
          "bg-background min-h-screen font-sans antialiased",
          montserrat.variable
        )}
      >
        {children}
        <ToastProvider />
      </body>
    </html>
  );
}
